// This file acts as a single source of truth for `systeminformation` commands used by
// the menu selector on the System Info page. Changes to labels can be done here, but
// cmd and id require changes on the backend and throughout the UI where ids are used.

export default [
  { id: '/', cmd: 'getAllData', label: 'All Data' },
  { id: 'a', cmd: 'audio', label: 'Audio' },
  { id: 'B', cmd: 'baseboard', label: 'Baseboard' },
  { id: 'Y', cmd: 'battery', label: 'Battery' },
  { id: 'b', cmd: 'bios', label: 'Bios' },
  { id: 'e', cmd: 'blockDevices', label: 'Block Devices' },
  { id: 'h', cmd: 'bluetoothDevices', label: 'Bluetooth Devices' },
  { id: 'C', cmd: 'chassis', label: 'Chassis' },
  { id: 'c', cmd: 'cpu', label: 'CPU' },
  { id: 'j', cmd: 'cpuCurrentSpeed', label: 'CPU Current Speed' },
  { id: 'T', cmd: 'cpuTemperature', label: 'CPU Temperature' },
  { id: 'l', cmd: 'currentLoad', label: 'Current Load' },
  { id: 'd', cmd: 'diskLayout', label: 'Disk Layout' },
  { id: 'D', cmd: 'disksIO', label: 'Disks IO' },
  {
    id: '0',
    cmd: 'dockerContainerProcesses',
    label: 'Docker Container Processes'
  },
  { id: '8', cmd: 'dockerContainers', label: 'Docker Containers' },
  { id: '9', cmd: 'dockerContainerStats', label: 'Docker Container Stats' },
  { id: '7', cmd: 'dockerImages', label: 'Docker Images' },
  { id: '6', cmd: 'dockerInfo', label: 'Docker Info' },
  { id: '+', cmd: 'dockerVolumes', label: 'Docker Volumes' },
  { id: 'E', cmd: 'fsOpenFiles', label: 'Fs Open Files' },
  { id: 'f', cmd: 'fsSize', label: 'Fs Size' },
  { id: 'F', cmd: 'fsStats', label: 'Fs Stats' },
  { id: 'L', cmd: 'fullLoad', label: 'Full Load' },
  { id: '.', cmd: 'getStaticData', label: 'Get Static Data' },
  { id: 'g', cmd: 'graphics', label: 'Graphics' },
  { id: 'i', cmd: 'inetLatency', label: 'Inet Latency' },
  { id: 'm', cmd: 'mem', label: 'Mem' },
  { id: 'M', cmd: 'memLayout', label: 'Mem Layout' },
  { id: '5', cmd: 'networkConnections', label: 'Network Connections' },
  { id: '2', cmd: 'networkGatewayDefault', label: 'Network Gateway Default' },
  {
    id: '1',
    cmd: 'networkInterfaceDefault',
    label: 'Network Interface Default'
  },
  { id: '3', cmd: 'networkInterfaces', label: 'Network Interfaces' },
  { id: '4', cmd: 'networkStats', label: 'Network Stats' },
  { id: 'o', cmd: 'osInfo', label: 'Os Info' },
  { id: 'r', cmd: 'printer', label: 'Printer' },
  { id: 'p', cmd: 'processes', label: 'Processes' },
  { id: 'S', cmd: 'shell', label: 'Shell' },
  { id: 'y', cmd: 'system', label: 'System' },
  { id: 'w', cmd: 'wifiNetworks', label: 'Wifi Networks' },
  { id: 'u', cmd: 'usb', label: 'USB' },
  { id: 'z', cmd: 'users', label: 'Users' },
  { id: 'U', cmd: 'uuid', label: 'UUID' },
  { id: 'V', cmd: 'vboxInfo', label: 'VBox Info' },
  { id: 'v', cmd: 'versions', label: 'Versions' },
  { id: 'x', cmd: 'wifiConnections', label: 'Wifi Connections' },
  { id: 'W', cmd: 'wifiInterfaces', label: 'Wifi Interfaces' }
]
