changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
      - weblate
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Documentation
      labels:
        - Documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
