## Build environment
FROM node:16.13.2-alpine3.15

RUN apk add rsync --no-cache

ENV NODE_ENV=development

# Specify that this is being deployed to a Balena device
ENV ON_DEVICE=true

# Enable corepack for alternative Yarn versions
RUN corepack enable

# Set working directory for distribution
WORKDIR /build/dist

# Copy required files for installs
COPY package.json .
COPY yarn.lock .
COPY .yarn .yarn
COPY .yarnrc.yml .
COPY expressjs/package.json expressjs/package.json
COPY ui/package.json ui/package.json

# Install packages
RUN yarn install --immutable

# Copy app in to container
COPY expressjs expressjs
COPY ui ui

# Used to identify whether a new build has been pushed and updates are required. Otherwise
# a container reinstall by Supervisor could overwrite your changes to the files when the container
# being installed hasn't changed. 
RUN echo $(date +%s) > .build_timestamp

# Switch to primary build directory
WORKDIR /build

# Copy the development scripts required for launch
COPY development .

# Run the start script
CMD ["sh", "start.sh"]
