version: "2.1"

services:
  balena-device-ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NETWORK_MODE: bridge # Tell the app if running in `bridge` or `host` network mode
      ON_DEVICE: "true" # Specify that this is being deployed to hardware with Balena OS
      BACKEND_PORT: 3000 # Change port to allow room for UI to be on port 80
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - "dev_app:/app"

    # If using the Volume Manager to access volumes on other containers, ensure this container `depends_on` your
    # other container using the below:
    # depends_on:
    #  - "your-other-container-name"

    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  nfs:
    environment:
      SYNC: False
      NFS_EXPORT_0: "/nfs *(rw,sync,no_subtree_check,no_auth_nlm,insecure,all_squash,anonuid=0,anongid=0,fsid=root)"
    image: ghcr.io/maggie0002/docker-nfs
    network_mode: "host"
    restart: always
    depends_on:
      - balena-device-ui
    volumes:
      - "dev_app:/nfs"
    cap_add:
      - SYS_ADMIN

  ## Optional Wi-Fi controller:
  ## https://github.com/maggie0002/balena-py-wifi-connect
  py-wifi-connect:
    environment:
      ## Listening IP and port ##
      PWC_HOST: bridge
      PWC_PORT: 9090

      ## Hotspot details ##
      PWC_HOTSPOT_SSID: "Balena Device UI"

      ## Required system variables ##
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    image: ghcr.io/maggie0002/py-wifi-connect
    network_mode: "host"
    restart: always
    volumes:
      - "pwc_db:/app/db" # Optional if not setting the hotspot ssid and password via the API
    labels:
      io.balena.features.dbus: "1"
    cap_add:
      - NET_ADMIN
    privileged: true # This can be removed if you do not need the LED indicator.

volumes:
  dev_app:
  pwc_db:
