name: "Deploy Docs"

on:
  push:
    branches:
      - main
      - master
    paths:
      - "docs/**"

  workflow_dispatch:

jobs:
  build:
    name: "Deploy-Docs"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      # Used to deploy the ./docs folder to GitHub pages. See https://github.com/balena-io-experimental/labs-docs-builder for more
      # details on its use. 
      - name: Build and deploy the docs
        uses: "balena-io-experimental/labs-docs-builder@main"
        with:
          git_pass: ${{ secrets.github_token }}
