name: "Deploy to development devices"
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy-to-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Balena
        uses: balena-io/deploy-to-balena-action@master
        id: build
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          fleet: balena_device_ui/balena-device-ui-testing

      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
