name: "Deploy to development devices"
on:
  pull_request:
    branches:
      - main

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job_name: ["rpi", "nuc"]

        include:
          - job_name: rpi
            fleet: bdi/bdi-rpi

          - job_name: nuc
            fleet: bdi/bdi-nuc

          #- job_name: fin
          #  fleet: bdi/bdi-fin

    name: ${{ matrix.job_name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: balena CLI Action
        uses: balena-community/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            push ${{ matrix.fleet }} --release-tag PR "${{ env.PR_NUMBER }}" commit-sha "${{ github.event.pull_request.head.sha }}";
          balena_cli_version: 13.7.1
