# Deploy pull requests to the test fleet automatically
name: "Deploy to development devices"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      # Fleet types to deploy to based on their architecture
      matrix:
        job_name: ["fin", "generic", "rpi"]

        include:
          - job_name: fin
            fleet: bdi/bdi-fin

          - job_name: generic
            fleet: bdi/bdi-generic

          - job_name: rpi
            fleet: bdi/bdi-rpi

    name: ${{ matrix.job_name }}

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      # Used to deploy to balena. See https://github.com/balena-labs-research/community-cli-action for more 
      # details. 
      - name: Balena CLI Action
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            push ${{ matrix.fleet }} --release-tag PR "${{ env.PR_NUMBER }}" commit-sha "${{ github.event.pull_request.head.sha }}";
          balena_cli_version: 14.5.15
