name: Deploy to BCR

on:
  push:
    tags:
      - "*"

jobs:
  deploy-to-bcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: balena CLI Action
        uses: balena-community/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: >
            maggie0002/balena-device-ui;
          balena_cli_version: 13.7.1

      - name: Log release ID built
        run: echo "Built release ID ${{ steps.build.outputs.release_id }}"
