# GitHub Workflow to manually build the Electron test app. The built assets are not notarised as they are not for distribution 
# and they are stored in the workflow as GitHub assets rather than published.

name: "Build Test Electron App"

on:
  pull_request:
    paths-ignore:
      - "docs/**"

env:
  ELECTRON_SKIP_NOTARIZATION: true

jobs:
  build-electron-app:
    timeout-minutes: 90
    env:
      ELECTRON_OUTPUT_PATH: "ui/dist/electron/Packaged"
      # Specify that this is being built for use locally and not on a device.
      ON_DEVICE: false
    strategy:
      fail-fast: false
      matrix:
        job_name: ["linux", "mac_amd64", mac_arm64, "windows"]

        include:
          - job_name: linux
            os: ubuntu-latest

          - job_name: mac_amd64
            os: macos-latest
            apple_signing: true

          - job_name: mac_arm64
            os: macos-latest
            build_arch: --arch arm64
            apple_signing: true

          - job_name: windows
            os: windows-latest

    name: ${{ matrix.job_name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          cache: "yarn"

      - name: Install UI packages
        run: |
          yarn install --frozen-lockfile

      - name: Install Electron Builder packages
        run: |
          yarn install --frozen-lockfile --cwd builder/

      - name: Build Electron app
        run: yarn build-electron ${{ matrix.build_arch }}

      - name: Upload artifacts to GitHub temporary storage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.job_name }}
          path: |
            ${{ env.ELECTRON_OUTPUT_PATH }}/*.exe
            ${{ env.ELECTRON_OUTPUT_PATH }}/*.dmg
            ${{ env.ELECTRON_OUTPUT_PATH }}/*.AppImage
