# GitHub Workflow to manually build the Electron test app. The built assets are not notarised as they are not for distribution 
# and they are stored in the workflow as GitHub assets rather than published.

name: "Build Test Electron App"

on:
  workflow_dispatch:

env:
  # When true, do not send the files to Apple for notarising. 
  ELECTRON_SKIP_NOTARIZATION: true
  # Specify that this is being built for use locally and not on a device. 
  ON_DEVICE: false

jobs:
  build:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job_name: ["linux", "mac_amd64", mac_arm64, "windows"]

        include:
          - job_name: linux
            os: ubuntu-latest

          - job_name: mac_amd64
            os: macos-latest
            apple_signing: true

          - job_name: mac_arm64
            os: macos-latest
            build_arch: --arch arm64
            apple_signing: true

          - job_name: windows
            os: windows-latest

    name: ${{ matrix.job_name }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
          cache: "yarn"

      - name: Install the Apple certificates
        if: ${{ matrix.apple_signing }}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install UI packages
        run: |
          yarn install --immutable

      - name: Install Electron Builder packages
        run: |
          yarn install --immutable --cwd builder/

      - name: Build Electron app
        env:
          XCODE_APP_LOADER_EMAIL: ${{ secrets.XCODE_APP_LOADER_EMAIL }}
          XCODE_APP_LOADER_PASSWORD: ${{ secrets.XCODE_APP_LOADER_PASSWORD }}
        run: yarn build-electron ${{ matrix.build_arch }}

      - name: Upload artifacts to GitHub temporary storage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.job_name }}
          path: |
            ui/dist/electron/Packaged/Balena Starter Interface*.exe
            ui/dist/electron/Packaged/Balena Starter Interface*.dmg
            ui/dist/electron/Packaged/Balena Starter Interface*.AppImage
