name: ESLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: corepack enable
      - run: yarn install --immutable
      - run: yarn lint
      - run: yarn formatcheck
